### ISSUE TITLE
[Logo Request]: ynETH

### ISSUE THREAD

**Issue by amadeobrands** [stake-dao/assets#2]
### Name

YieldNest ETH

### Symbol

ynETH

### Logo URL

https://assets.yieldnest.finance/images/ynETH.svg

### Chains

Ethereum

### Addresses

Ethereum : 0x09db87a538bd693e9d08544577d5ccfaa6373a48

**Comment by 0xVe** [comment]
271edfb4913883abbde113e0de0fa20da1deec1e
