### ISSUE TITLE
[Logo Request]: Zunami Governance Token

### ISSUE THREAD

**Issue by nikita-plotnikov-fl** [stake-dao/assets#4]
### Name

Zunami Governance Token

### Symbol

ZUN

### Logo URL

https://app.zunami.io/zun.svg

### Chains

Ethereum, Arbitrum, Base

### Addresses

Ethereum: 0x6b5204b0be36771253cc38e88012e02b752f0f36
Arbitrum: 0x346e74dc9935a9b02eb34fb84658a66010fa056d
Base: 0x1db0fc8933f545648b54a9ee4326209a9a259643

**Comment by 0xVe** [comment]
06c0386fa34a9b2d35431177278369811eacb5e8
