### ISSUE TITLE
[Logo Request]: Zunami ETH

### ISSUE THREAD

**Issue by nikita-plotnikov-fl** [stake-dao/assets#5]
### Name

Zunami ETH

### Symbol

ZUNETH

### Logo URL

https://app.zunami.io/zuneth.svg

### Chains

Ethereum, Arbitrum

### Addresses

Ethereum: 0xc2e660c62f72c2ad35ace6db78a616215e2f2222
Arbitrum: 0x06d65ec13465ac5a4376dc101e1141252c4addf8

**Comment by 0xVe** [comment]
5da889505df9f4e9886d627272bb1e11bea4f7ca
